name: terraform-version
description: Prints terraform and providers versions
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .

outputs:
  version:
    description: The terraform version used by the configuration

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:4fec008558a518785e1ac10e1f601a584d2642a013e871f2c50134f7ed14f361
  entrypoint: /entrypoints/version.sh

branding:
  icon: globe
  color: purple
