name: terraform-version
description: Prints terraform and providers versions
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .

outputs:
  version:
    description: The terraform version used by the configuration

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:9df1c05b684e3efe287162baa09a1db81a50ba94a295e2bdf1f8a375bf2bbd3f
  entrypoint: /entrypoints/version.sh

branding:
  icon: globe
  color: purple
