name: terraform-version
description: Prints terraform and providers versions
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .
  workspace:
    description: Name of the terraform workspace to get the version for
    required: false
    default: default
  backend_config:
    description: List of backend config values to set, one per line
    required: false
    default: ""
  backend_config_file:
    description: Path to a backend config file
    required: false
    default: ""

outputs:
  version:
    description: The terraform version used by the configuration

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:6d31b0d1bcc8c2073032f8e38819cba219adca58927acc6e610a83e7927269b4
  entrypoint: /entrypoints/version.sh

branding:
  icon: globe
  color: purple
